site_name: Monggregate Documentation
site_url: https://vianneymi.github.io/monggregate/
nav:
  - Home: index.md
  - Intro:
    - MongoDB Umbrella: intro/mongodb-umbrella.md
    - MongoDB Aggregation Framework: intro/mongodb-aggregation-framework.md
    - Why use Monggregate ?: intro/why-use-monggregate.md
  - Tutorial:
    - Getting Started: tutorial/getting-started.md
  #- API Reference: api.md
  - Changelog: changelog.md

# # Using mkdocstrings to generate documentation from docstrings (API Reference)
# plugins:
#   - mkdocstrings


# Using the Material theme for styling
theme: material
  # Material Options for syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

