site_name: Monggregate Documentation
site_url: https://example.com/
nav:
  - Home: index.md
  - API Reference: api.md
  - Changelog: changelog.md

# Using mkdocstrings to generate documentation from docstrings (API Reference)
plugins:
  - mkdocstrings


# Using the Material theme for styling
theme: material
  # Material Options for syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

