# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monggregate"
version = "0.2.0"
description = "Interface to ease creation and usage of MongoDB aggregation pipelines in python"
readme = "README.md"
authors = [{ name = "Vianney Mixtur", email = "vianney.mixtur@outlook.fr" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["nosql", "mongo", "aggregation", "pymongo", "pandas", "pydantic"]
dependencies = [
    "pydantic >= 1.8.0",
    "pymongo >= 3.0",
]
requires-python = ">=3.10"
